// ══════════════════════════════════════════════════════════════════════════════
//  STUDENT.JS — Module Étudiant
//  Programme hebdomadaire intelligent avec sessions d'étude auto-générées
// ══════════════════════════════════════════════════════════════════════════════

// ── State ───────────────────────────────────────────────────────────────────
let studentPrefs = null;
// { studyTime: 'morning'|'evening', travelTo: 30, travelFrom: 45,
//   studyHoursWeekday: 2, studyHoursLight: 1, onboardingDone: true }

let studentSchedule = {};
// { 'monday': [ {id, type:'cours'|'autre'|'study', name, start:'08:00', end:'10:00',
//                importance:'high'|'medium'|'other', color, autoGenerated:bool} ] }

let editingCourseDay = null;
let editingCourseId  = null;
let selectedCourseType = 'cours';
let selectedCourseImp  = 'high';
let selectedCourseColor = '#2563eb';

const DAYS_FR = ['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'];
const DAYS_EN = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
const HOURS_START = 6;  // programme de 6h à 23h
const HOURS_END   = 23;
const PX_PER_MIN  = 1.2; // hauteur en px par minute

// ── Navigation ───────────────────────────────────────────────────────────────
window.goToStudent = async () => {
  document.querySelectorAll('.screen').forEach(s => s.classList.remove('active'));
  document.getElementById('screen-student').classList.add('active');
  document.getElementById('fab-add').style.display = 'none';
  document.getElementById('topbar-title').textContent = '🎓 Étudiant';
  await loadStudentData();
  if (!studentPrefs?.onboardingDone) {
    startOnboarding();
  } else {
    renderStudentSchedule();
  }
};

// ── Chargement ───────────────────────────────────────────────────────────────
async function loadStudentData() {
  const cachedPrefs    = await idbGet('prefs', 'studentPrefs');
  const cachedSchedule = await idbGet('prefs', 'studentSchedule');
  if (cachedPrefs?.value)    studentPrefs    = cachedPrefs.value;
  if (cachedSchedule?.value) studentSchedule = cachedSchedule.value;
  if (currentUser) {
    try {
      const snap = await getDoc(doc(db, 'users', currentUser.uid));
      if (snap.exists()) {
        const d = snap.data();
        if (d.studentPrefs)    studentPrefs    = d.studentPrefs;
        if (d.studentSchedule) studentSchedule = d.studentSchedule;
        await idbPut('prefs', { key: 'studentPrefs',    value: studentPrefs });
        await idbPut('prefs', { key: 'studentSchedule', value: studentSchedule });
      }
    } catch(e) {}
  }
}

async function saveStudentData() {
  await idbPut('prefs', { key: 'studentPrefs',    value: studentPrefs });
  await idbPut('prefs', { key: 'studentSchedule', value: studentSchedule });
  if (currentUser) {
    updateDoc(doc(db, 'users', currentUser.uid), { studentPrefs, studentSchedule }).catch(() => {});
  }
}

// ── ONBOARDING ────────────────────────────────────────────────────────────────
const ONBOARDING_STEPS = [
  {
    emoji: '🎓',
    title: 'Bienvenue, étudiant.',
    sub: 'Trivo va construire ton programme de la semaine automatiquement.\nTu n\'as qu\'à ajouter tes cours — le reste, c\'est nous.',
    type: 'intro'
  },
  {
    emoji: '🌅',
    title: 'Tu préfères étudier quand ?',
    sub: 'On va planifier tes sessions d\'étude selon ta préférence.',
    type: 'choice',
    key: 'studyTime',
    options: [
      { value: 'morning', label: '🌅 Tôt le matin', sub: 'Avant les cours ou en début de journée' },
      { value: 'evening', label: '🌙 Le soir',      sub: 'Après les cours, quand tu es rentré' }
    ]
  },
  {
    emoji: '🚌',
    title: 'Combien de temps pour aller à l\'école ?',
    sub: 'En minutes. On en tiendra compte pour ton réveil et tes horaires.',
    type: 'number',
    key: 'travelTo',
    placeholder: 'Ex: 30',
    unit: 'minutes'
  },
  {
    emoji: '🏠',
    title: 'Et pour rentrer chez toi ?',
    sub: 'En minutes après la fin des cours.',
    type: 'number',
    key: 'travelFrom',
    placeholder: 'Ex: 45',
    unit: 'minutes'
  },
  {
    emoji: '📚',
    title: 'Combien d\'heures d\'étude les jours ordinaires ?',
    sub: 'Lundi au jeudi — les jours chargés.',
    type: 'number',
    key: 'studyHoursWeekday',
    placeholder: 'Ex: 2',
    unit: 'heures'
  },
  {
    emoji: '🧘',
    title: 'Et les jours plus légers ?',
    sub: 'Vendredi, samedi, dimanche — un peu de liberté.',
    type: 'number',
    key: 'studyHoursLight',
    placeholder: 'Ex: 1',
    unit: 'heures'
  },
  {
    emoji: '✅',
    title: 'Tout est prêt.',
    sub: 'Ajoute maintenant tes cours dans le programme. Trivo s\'occupe du reste — réveil, étude, temps libre.',
    type: 'finish'
  }
];

let onboardingStep = 0;
let onboardingAnswers = {};

function startOnboarding() {
  onboardingStep = 0;
  onboardingAnswers = {};
  const overlay = document.getElementById('student-onboarding');
  overlay.style.display = 'flex';
  renderOnboardingStep();
}

function renderOnboardingStep() {
  const step = ONBOARDING_STEPS[onboardingStep];
  const total = ONBOARDING_STEPS.length;

  // Progress dots
  const progressEl = document.getElementById('onboarding-progress');
  progressEl.innerHTML = ONBOARDING_STEPS.map((_, i) =>
    `<div class="onboarding-dot ${i <= onboardingStep ? 'done' : ''}"></div>`
  ).join('');

  const wrap = document.getElementById('onboarding-steps-wrap');
  let html = `
    <div class="onboarding-step active">
      <div class="onboarding-emoji">${step.emoji}</div>
      <div class="onboarding-title">${step.title}</div>
      <div class="onboarding-sub">${step.sub.replace(/\n/g, '<br>')}</div>`;

  if (step.type === 'choice') {
    html += `<div class="onboarding-options">
      ${step.options.map(o => `
        <div class="onboarding-option ${onboardingAnswers[step.key]===o.value?'selected':''}"
             onclick="selectOnboardingChoice('${step.key}','${o.value}',this)">
          ${o.label}<br><span style="font-size:12px;opacity:0.7;">${o.sub}</span>
        </div>`).join('')}
    </div>`;
    html += `<button class="onboarding-next" onclick="nextOnboardingStep()" style="margin-top:16px;">Continuer →</button>`;
  } else if (step.type === 'number') {
    html += `<input class="onboarding-input" type="number" min="1" max="120"
      id="onboarding-number-input" value="${onboardingAnswers[step.key]||''}"
      placeholder="${step.placeholder}" />
    <div style="font-size:13px;color:var(--text3);margin-top:6px;">${step.unit}</div>
    <button class="onboarding-next" onclick="nextOnboardingStepNumber('${step.key}')">Continuer →</button>`;
  } else if (step.type === 'finish') {
    html += `<button class="onboarding-next" onclick="finishOnboarding()">Voir mon programme 🎓</button>`;
  } else {
    html += `<button class="onboarding-next" onclick="nextOnboardingStep()">Commencer →</button>`;
  }

  html += `</div>`;
  wrap.innerHTML = html;

  if (step.type === 'number') {
    setTimeout(() => document.getElementById('onboarding-number-input')?.focus(), 300);
  }
}

window.selectOnboardingChoice = (key, value, el) => {
  onboardingAnswers[key] = value;
  el.closest('.onboarding-options').querySelectorAll('.onboarding-option').forEach(o => o.classList.remove('selected'));
  el.classList.add('selected');
};

window.nextOnboardingStep = () => {
  const step = ONBOARDING_STEPS[onboardingStep];
  if (step.type === 'choice' && !onboardingAnswers[step.key]) {
    showToast('Fais un choix pour continuer'); return;
  }
  onboardingStep++;
  if (onboardingStep < ONBOARDING_STEPS.length) renderOnboardingStep();
};

window.nextOnboardingStepNumber = (key) => {
  const val = parseInt(document.getElementById('onboarding-number-input')?.value);
  if (!val || val < 1) { showToast('Entre un nombre valide'); return; }
  onboardingAnswers[key] = val;
  onboardingStep++;
  if (onboardingStep < ONBOARDING_STEPS.length) renderOnboardingStep();
};

window.finishOnboarding = async () => {
  studentPrefs = {
    studyTime:         onboardingAnswers.studyTime || 'evening',
    travelTo:          onboardingAnswers.travelTo  || 30,
    travelFrom:        onboardingAnswers.travelFrom || 45,
    studyHoursWeekday: onboardingAnswers.studyHoursWeekday || 2,
    studyHoursLight:   onboardingAnswers.studyHoursLight   || 1,
    onboardingDone:    true
  };
  if (!studentSchedule || !Object.keys(studentSchedule).length) {
    studentSchedule = {};
    DAYS_EN.forEach(d => { studentSchedule[d] = []; });
  }
  await saveStudentData();
  document.getElementById('student-onboarding').style.display = 'none';
  renderStudentSchedule();
  showToast('Programme créé. Ajoute maintenant tes cours.');
};

// ── RENDU DU PROGRAMME ────────────────────────────────────────────────────────
function renderStudentSchedule() {
  const scheduleEl = document.getElementById('student-schedule');
  const labelsEl   = document.getElementById('student-hour-labels');
  if (!scheduleEl) return;

  const totalH   = HOURS_END - HOURS_START;
  const totalPx  = totalH * 60 * PX_PER_MIN;

  // Étiquettes heures
  if (labelsEl) {
    labelsEl.style.height = totalPx + 40 + 'px';
    labelsEl.innerHTML = '';
    for (let h = HOURS_START; h <= HOURS_END; h++) {
      const top = (h - HOURS_START) * 60 * PX_PER_MIN;
      const el = document.createElement('div');
      el.style.cssText = `position:absolute;top:${top}px;font-size:8px;color:var(--text3);right:2px;transform:translateY(-50%);`;
      el.textContent = `${h}h`;
      labelsEl.appendChild(el);
    }
  }

  // Colonnes jours
  const today = new Date().getDay(); // 0=dim, 1=lun...
  scheduleEl.innerHTML = '';
  DAYS_EN.forEach((dayKey, idx) => {
    const jsDayIdx = idx === 6 ? 0 : idx + 1; // lundi=1,..., dimanche=0
    const isToday = today === jsDayIdx;
    const blocks = (studentSchedule[dayKey] || [])
      .concat(getAutoStudyBlocks(dayKey));

    const col = document.createElement('div');
    col.className = 'student-day-col';
    col.innerHTML = `<div class="student-day-header ${isToday?'today':''}">${DAYS_FR[idx].slice(0,3)}</div>
      <div class="student-timeline" style="height:${totalPx}px;" id="timeline-${dayKey}"></div>`;
    scheduleEl.appendChild(col);

    // Lignes d'heure
    const timeline = col.querySelector(`#timeline-${dayKey}`);
    for (let h = HOURS_START; h <= HOURS_END; h++) {
      const line = document.createElement('div');
      line.className = 'student-hour-line';
      line.style.top = (h - HOURS_START) * 60 * PX_PER_MIN + 'px';
      timeline.appendChild(line);
    }

    // Slot cliquable (toute la colonne)
    const slotOverlay = document.createElement('div');
    slotOverlay.style.cssText = `position:absolute;inset:0;z-index:1;`;
    slotOverlay.onclick = (e) => {
      const rect = e.currentTarget.getBoundingClientRect();
      const y = e.clientY - rect.top;
      const minutes = Math.round(y / PX_PER_MIN / 30) * 30;
      const h = HOURS_START + Math.floor(minutes / 60);
      const m = minutes % 60;
      openAddCourseModal(dayKey, `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);
    };
    timeline.appendChild(slotOverlay);

    // Blocs
    blocks.forEach(block => {
      const el = buildBlockElement(block, dayKey);
      if (el) timeline.appendChild(el);
    });
  });
}

function buildBlockElement(block, dayKey) {
  const startMin = timeToMin(block.start);
  const endMin   = timeToMin(block.end);
  if (startMin < HOURS_START * 60 || endMin > HOURS_END * 60) return null;

  const top    = (startMin - HOURS_START * 60) * PX_PER_MIN;
  const height = Math.max((endMin - startMin) * PX_PER_MIN, 20);

  const el = document.createElement('div');
  el.className = `student-block ${block.autoGenerated?'study':''} ${block.importance?'imp-'+block.importance:''}`;
  el.style.cssText = `top:${top}px;height:${height}px;z-index:2;`;
  if (block.color && !block.autoGenerated) el.style.background = block.color;
  if (block.autoGenerated) {
    el.style.background = 'linear-gradient(135deg,#1d4ed8,#1e40af)';
    el.style.borderLeft  = '3px solid #60a5fa';
  }

  el.innerHTML = `<div class="block-title">${block.name}</div>
    <div class="block-time">${block.start}–${block.end}</div>`;

  if (!block.autoGenerated) {
    el.style.zIndex = '3';
    el.onclick = (e) => { e.stopPropagation(); openEditCourseModal(dayKey, block.id); };
  }
  return el;
}

// ── AUTO-GÉNÉRATION DES SESSIONS D'ÉTUDE ─────────────────────────────────────
function getAutoStudyBlocks(dayKey) {
  if (!studentPrefs) return [];
  const dayIdx  = DAYS_EN.indexOf(dayKey);
  const isLight = dayIdx >= 4; // ven=4, sam=5, dim=6
  const studyH  = isLight ? studentPrefs.studyHoursLight : studentPrefs.studyHoursWeekday;
  const courses = (studentSchedule[dayKey] || []).filter(b => b.type === 'cours');

  if (!courses.length || studyH <= 0) return [];

  courses.sort((a, b) => timeToMin(a.start) - timeToMin(b.start));
  const lastCourse = courses[courses.length - 1];
  const returnMin  = timeToMin(lastCourse.end) + studentPrefs.travelFrom;

  // Important : on laisse 1h30 de buffer après le retour (douche, repas, etc.)
  const bufferMin  = returnMin + 90;

  // Trouver les trous dans le programme (pauses entre cours) — on ne les utilise pas
  const studyStart = studentPrefs.studyTime === 'morning'
    ? courses[0] ? timeToMin(courses[0].start) - studentPrefs.travelTo - studyH * 60 - 30 : 6 * 60
    : bufferMin;

  if (studyStart < HOURS_START * 60 || studyStart + studyH * 60 > HOURS_END * 60) return [];

  const start = minToTime(studyStart);
  const end   = minToTime(studyStart + studyH * 60);

  return [{
    id: `auto-study-${dayKey}`,
    type: 'study',
    name: 'Révision',
    start, end,
    autoGenerated: true
  }];
}

// ── GÉNÉRATION DES TÂCHES D'ÉTUDE DANS TRIVO ─────────────────────────────────
window.generateStudyPlan = async () => {
  if (!studentPrefs?.onboardingDone) return;
  const today = new Date();
  const weekStart = new Date(today);
  weekStart.setDate(today.getDate() - ((today.getDay() + 6) % 7)); // lundi

  let addedCount = 0;
  for (let i = 0; i < 7; i++) {
    const d = new Date(weekStart); d.setDate(weekStart.getDate() + i);
    const dayKey   = DAYS_EN[i];
    const dateStr  = window.fmtDate ? window.fmtDate(d) : d.toISOString().slice(0,10);
    const autoBlocks = getAutoStudyBlocks(dayKey);

    for (const block of autoBlocks) {
      // Vérifier si une tâche d'étude existe déjà pour ce jour
      const alreadyExists = tasks.some(t =>
        t.date === dateStr && t.studentStudy === true && t.studentDay === dayKey
      );
      if (alreadyExists) continue;

      const now   = Date.now();
      const newId = `study-${dayKey}-${now}-${Math.random().toString(36).slice(2,6)}`;
      const newTask = {
        id: newId, uid: currentUser.uid,
        title: `Révision — ${DAYS_FR[i]}`,
        content: `Session d'étude automatique : ${block.start} – ${block.end}`,
        date: dateStr, time: block.start,
        status: 'pending', color: '#1d4ed8',
        studentStudy: true, studentDay: dayKey,
        timestamp: now, updatedAt: now
      };
      await idbPut('tasks', newTask);
      tasks.unshift(newTask);
      await queuePush('create', 'tasks', newId, newTask);
      addedCount++;
    }
  }
  if (navigator.onLine) await window.queueFlush();
  renderTaskList?.();
  showToast(addedCount > 0 ? `${addedCount} session${addedCount>1?'s':''} d'étude ajoutée${addedCount>1?'s':''} à tes tâches` : 'Programme à jour');
};

// ── MODAL AJOUT / MODIFICATION COURS ─────────────────────────────────────────
window.openAddCourseModal = (dayKey, defaultStart = '08:00') => {
  editingCourseDay = dayKey;
  editingCourseId  = null;
  selectedCourseType  = 'cours';
  selectedCourseImp   = 'high';
  selectedCourseColor = '#2563eb';

  document.getElementById('course-modal-title').textContent = `Ajouter — ${DAYS_FR[DAYS_EN.indexOf(dayKey)]}`;
  document.getElementById('course-name-input').value = '';
  document.getElementById('course-start-input').value = defaultStart;
  document.getElementById('course-end-input').value = addMinutes(defaultStart, 60);
  document.getElementById('course-delete-btn').style.display = 'none';
  document.getElementById('course-importance-wrap').style.opacity = '1';
  selectCourseType('cours');
  document.getElementById('student-course-modal').classList.add('open');
};

window.openEditCourseModal = (dayKey, courseId) => {
  const course = (studentSchedule[dayKey] || []).find(c => c.id === courseId);
  if (!course) return;

  editingCourseDay    = dayKey;
  editingCourseId     = courseId;
  selectedCourseType  = course.type;
  selectedCourseImp   = course.importance || 'high';
  selectedCourseColor = course.color || '#2563eb';

  document.getElementById('course-modal-title').textContent = `Modifier — ${DAYS_FR[DAYS_EN.indexOf(dayKey)]}`;
  document.getElementById('course-name-input').value  = course.name;
  document.getElementById('course-start-input').value = course.start;
  document.getElementById('course-end-input').value   = course.end;
  document.getElementById('course-delete-btn').style.display = 'block';
  selectCourseType(course.type);
  // Sélectionner l'importance
  document.querySelectorAll('.course-imp-chip').forEach(c => {
    c.classList.toggle('selected', c.dataset.imp === selectedCourseImp);
  });
  document.getElementById('student-course-modal').classList.add('open');
};

window.selectCourseType = (type) => {
  selectedCourseType = type;
  document.getElementById('course-type-cours')?.classList.toggle('selected', type === 'cours');
  document.getElementById('course-type-autre')?.classList.toggle('selected', type === 'autre');
  const impWrap = document.getElementById('course-importance-wrap');
  if (impWrap) impWrap.style.opacity = type === 'cours' ? '1' : '0.4';
};

window.selectCourseImp = (imp, el) => {
  selectedCourseImp = imp;
  document.querySelectorAll('.course-imp-chip').forEach(c => c.classList.remove('selected'));
  el.classList.add('selected');
};

window.selectCourseColor = (color, el) => {
  selectedCourseColor = color;
  document.querySelectorAll('#course-color-picker .color-dot').forEach(d => {
    d.style.border = d.dataset.color === color ? '2px solid #fff' : '2px solid transparent';
  });
};

window.saveCourseBlock = async () => {
  const name  = document.getElementById('course-name-input').value.trim();
  const start = document.getElementById('course-start-input').value;
  const end   = document.getElementById('course-end-input').value;

  if (!name)  { showToast('Entre un nom'); return; }
  if (!start || !end) { showToast('Entre les heures'); return; }
  if (timeToMin(start) >= timeToMin(end)) { showToast('L\'heure de fin doit être après le début'); return; }

  if (!studentSchedule[editingCourseDay]) studentSchedule[editingCourseDay] = [];

  if (editingCourseId) {
    studentSchedule[editingCourseDay] = studentSchedule[editingCourseDay].map(c =>
      c.id === editingCourseId
        ? { ...c, name, start, end, type: selectedCourseType, importance: selectedCourseType==='cours'?selectedCourseImp:'other', color: selectedCourseColor }
        : c
    );
  } else {
    const newId = `course-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
    studentSchedule[editingCourseDay].push({
      id: newId, name, start, end,
      type: selectedCourseType,
      importance: selectedCourseType === 'cours' ? selectedCourseImp : 'other',
      color: selectedCourseColor
    });
  }

  await saveStudentData();
  closeModal('student-course-modal');
  renderStudentSchedule();
};

window.deleteCourseBlock = async () => {
  if (!editingCourseId || !editingCourseDay) return;
  if (!confirm('Supprimer ce cours ?')) return;
  studentSchedule[editingCourseDay] = (studentSchedule[editingCourseDay] || [])
    .filter(c => c.id !== editingCourseId);
  await saveStudentData();
  closeModal('student-course-modal');
  renderStudentSchedule();
};

// ── PARAMÈTRES ÉTUDIANT ───────────────────────────────────────────────────────
window.openStudentSettings = () => {
  const panel = document.getElementById('student-settings-panel');
  if (!panel) return;
  renderStudentSettingsContent();
  panel.classList.add('open');
};

window.closeStudentSettings = () => {
  document.getElementById('student-settings-panel')?.classList.remove('open');
};

function renderStudentSettingsContent() {
  const el = document.getElementById('student-settings-content');
  if (!el || !studentPrefs) return;
  el.innerHTML = `
    <div style="display:flex;flex-direction:column;gap:20px;">

      <div class="card" style="padding:16px;">
        <div class="field-label" style="margin-bottom:10px;">Heure d'étude préférée</div>
        <div style="display:flex;gap:10px;">
          <button class="onboarding-option ${studentPrefs.studyTime==='morning'?'selected':''}"
            style="flex:1;padding:10px;font-size:13px;" onclick="updateStudentPref('studyTime','morning',this)">🌅 Matin</button>
          <button class="onboarding-option ${studentPrefs.studyTime==='evening'?'selected':''}"
            style="flex:1;padding:10px;font-size:13px;" onclick="updateStudentPref('studyTime','evening',this)">🌙 Soir</button>
        </div>
      </div>

      <div class="card" style="padding:16px;">
        <div class="field-label">Trajet pour aller à l'école</div>
        <div style="display:flex;align-items:center;gap:10px;margin-top:8px;">
          <input class="field-input" type="number" min="0" max="120" value="${studentPrefs.travelTo}"
            id="pref-travelTo" style="flex:1;" />
          <span style="color:var(--text3);font-size:13px;">min</span>
        </div>
        <div class="field-label" style="margin-top:12px;">Trajet pour rentrer</div>
        <div style="display:flex;align-items:center;gap:10px;margin-top:8px;">
          <input class="field-input" type="number" min="0" max="120" value="${studentPrefs.travelFrom}"
            id="pref-travelFrom" style="flex:1;" />
          <span style="color:var(--text3);font-size:13px;">min</span>
        </div>
      </div>

      <div class="card" style="padding:16px;">
        <div class="field-label">Heures d'étude — jours ordinaires (lun–jeu)</div>
        <div style="display:flex;align-items:center;gap:10px;margin-top:8px;">
          <input class="field-input" type="number" min="0" max="8" value="${studentPrefs.studyHoursWeekday}"
            id="pref-studyHoursWeekday" style="flex:1;" />
          <span style="color:var(--text3);font-size:13px;">h/jour</span>
        </div>
        <div class="field-label" style="margin-top:12px;">Heures d'étude — jours légers (ven–dim)</div>
        <div style="display:flex;align-items:center;gap:10px;margin-top:8px;">
          <input class="field-input" type="number" min="0" max="8" value="${studentPrefs.studyHoursLight}"
            id="pref-studyHoursLight" style="flex:1;" />
          <span style="color:var(--text3);font-size:13px;">h/jour</span>
        </div>
      </div>

      <button class="btn-primary" style="padding:14px;border-radius:14px;font-size:15px;font-weight:700;"
        onclick="saveStudentSettings()">Enregistrer les préférences</button>

      <button class="btn-secondary" style="padding:12px;border-radius:14px;font-size:13px;"
        onclick="if(confirm('Réinitialiser tout le programme étudiant ?')){studentPrefs=null;studentSchedule={};saveStudentData();closeStudentSettings();goToStudent();}">
        Réinitialiser le programme
      </button>
    </div>`;
}

window.updateStudentPref = (key, value, el) => {
  studentPrefs[key] = value;
  el.closest('div').querySelectorAll('.onboarding-option').forEach(b => b.classList.remove('selected'));
  el.classList.add('selected');
};

window.saveStudentSettings = async () => {
  studentPrefs.travelTo          = parseInt(document.getElementById('pref-travelTo')?.value)          || 30;
  studentPrefs.travelFrom        = parseInt(document.getElementById('pref-travelFrom')?.value)        || 45;
  studentPrefs.studyHoursWeekday = parseInt(document.getElementById('pref-studyHoursWeekday')?.value) || 2;
  studentPrefs.studyHoursLight   = parseInt(document.getElementById('pref-studyHoursLight')?.value)   || 1;
  await saveStudentData();
  closeStudentSettings();
  renderStudentSchedule();
  showToast('Préférences enregistrées');
};

// ── Helpers ──────────────────────────────────────────────────────────────────
function timeToMin(t) {
  if (!t) return 0;
  const [h, m] = t.split(':').map(Number);
  return h * 60 + m;
}
function minToTime(min) {
  const h = Math.floor(min / 60);
  const m = min % 60;
  return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;
}
function addMinutes(time, min) {
  return minToTime(timeToMin(time) + min);
}
